In [1]:
import pandas as pd

In [2]:
Trans = pd.read_excel (r'KPMG.xlsx', sheet_name='Transactions')
print (Trans)

       transaction_id  product_id  customer_id transaction_date  online_order  \
0                   1           2         2950       2017-02-25           0.0
1                   2           3         3120       2017-05-21           1.0
2                   3          37          402       2017-10-16           0.0
3                   4          88         3135       2017-08-31           0.0
4                   5          78          787       2017-10-01           1.0
5                   6          25         2339       2017-03-08           1.0
6                   7          22         1542       2017-04-21           1.0
7                   8          15         2459       2017-07-15           0.0
8                   9          67         1305       2017-08-10           0.0
9                  10          12         3262       2017-08-30           1.0
10                 11           5         1986       2017-01-17           0.0
11                 12          61         2783       2017-01-05           1.0
12                 13          35         1243       2017-02-26           1.0
13                 14          16         2717       2017-09-10           0.0
14                 15          12          247       2017-06-11           0.0
15                 16           3         2961       2017-10-10           0.0
16                 17          79         2426       2017-04-03           0.0
17                 18          33         1842       2017-06-02           0.0
18                 19          54         2268       2017-04-06           1.0
19                 20          25         3002       2017-01-28           1.0
20                 21          27         1582       2017-10-09           0.0
21                 22          37          595       2017-06-29           1.0
22                 23          37         2001       2017-04-08           1.0
23                 24          82          515       2017-10-18           0.0
24                 25          89         2822       2017-06-11           0.0
25                 26          64         2596       2017-01-10           0.0
26                 27          64         2666       2017-04-11           1.0
27                 28          19           76       2017-12-23           0.0
28                 29          72         3368       2017-10-13           1.0
29                 30          91         1173       2017-03-15           0.0
...               ...         ...          ...              ...           ...
19970           19971           1         1464       2017-03-18           0.0
19971           19972          46         2967       2017-05-10           0.0
19972           19973          39         1188       2017-05-13           1.0
19973           19974          80          148       2017-11-17           1.0
19974           19975          88         3129       2017-09-08           1.0
19975           19976          35         1700       2017-10-22           0.0
19976           19977          44         1102       2017-01-02           0.0
19977           19978          57          932       2017-10-08           1.0
19978           19979          27          333       2017-12-08           1.0
19979           19980          30         1435       2017-03-04           1.0
19980           19981          95         3304       2017-06-07           0.0
19981           19982          28         1075       2017-07-20           1.0
19982           19983          11         1137       2017-03-11           1.0
19983           19984          80          275       2017-07-02           0.0
19984           19985          31          873       2017-11-15           1.0
19985           19986          36         2918       2017-11-09           1.0
19986           19987          38         2385       2017-11-01           0.0
19987           19988           0           13       2017-04-05           1.0
19988           19989           0          714       2017-04-27           1.0
19989           19990          55          135       2017-01-27           1.0
19990           19991          78          425       2017-01-26           0.0
19991           19992          11         1374       2017-09-14           0.0
19992           19993          13            5       2017-04-28           0.0
19993           19994          77         2618       2017-12-23           0.0
19994           19995           9          718       2017-05-13           1.0
19995           19996          51         1018       2017-06-24           1.0
19996           19997          41          127       2017-11-09           1.0
19997           19998          87         2284       2017-04-14           1.0
19998           19999           6         2764       2017-07-03           0.0
19999           20000          11         1144       2017-09-22           1.0

      order_status           brand product_line product_class product_size  \
0         Approved           Solex     Standard        medium       medium
1         Approved   Trek Bicycles     Standard        medium        large
2         Approved      OHM Cycles     Standard           low       medium
3         Approved  Norco Bicycles     Standard        medium       medium
4         Approved  Giant Bicycles     Standard        medium        large
5         Approved  Giant Bicycles         Road        medium       medium
6         Approved        WeareA2B     Standard        medium       medium
7         Approved        WeareA2B     Standard        medium       medium
8         Approved           Solex     Standard        medium        large
9         Approved        WeareA2B     Standard        medium       medium
10        Approved   Trek Bicycles     Mountain           low       medium
11        Approved      OHM Cycles     Standard           low       medium
12        Approved   Trek Bicycles     Standard           low       medium
13        Approved  Norco Bicycles     Standard          high        small
14        Approved  Giant Bicycles     Standard        medium        large
15        Approved   Trek Bicycles     Standard        medium        large
16        Approved  Norco Bicycles     Standard        medium       medium
17        Approved  Giant Bicycles     Standard        medium        small
18        Approved        WeareA2B     Standard        medium       medium
19        Approved  Giant Bicycles         Road        medium       medium
20        Approved   Trek Bicycles     Standard        medium       medium
21        Approved      OHM Cycles     Standard           low       medium
22        Approved      OHM Cycles     Standard           low       medium
23        Approved  Giant Bicycles         Road        medium       medium
24        Approved        WeareA2B      Touring        medium        large
25        Approved   Trek Bicycles     Standard        medium        large
26        Approved   Trek Bicycles     Standard        medium        large
27        Approved   Trek Bicycles     Mountain           low       medium
28        Approved  Norco Bicycles     Standard        medium       medium
29        Approved        WeareA2B     Standard           low       medium
...            ...             ...          ...           ...          ...
19970     Approved  Giant Bicycles     Standard        medium       medium
19971     Approved           Solex     Standard           low       medium
19972     Approved  Giant Bicycles     Standard        medium        large
19973     Approved      OHM Cycles      Touring           low       medium
19974     Approved  Norco Bicycles     Standard          high        small
19975     Approved  Giant Bicycles     Standard        medium       medium
19976     Approved        WeareA2B     Standard        medium       medium
19977     Approved        WeareA2B      Touring        medium        large
19978     Approved   Trek Bicycles     Standard        medium       medium
19979     Approved           Solex     Standard          high       medium
19980     Approved  Giant Bicycles     Standard        medium        large
19981     Approved           Solex         Road        medium        small
19982     Approved  Giant Bicycles     Standard          high       medium
19983     Approved   Trek Bicycles     Standard        medium        large
19984     Approved  Giant Bicycles     Standard        medium       medium
19985     Approved           Solex     Standard           low       medium
19986     Approved           Solex     Standard        medium       medium
19987     Approved  Norco Bicycles         Road        medium       medium
19988     Approved  Norco Bicycles     Standard           low       medium
19989    Cancelled   Trek Bicycles         Road        medium        large
19990     Approved  Giant Bicycles     Standard        medium        large
19991     Approved  Giant Bicycles     Standard          high       medium
19992     Approved           Solex     Standard        medium       medium
19993     Approved  Norco Bicycles         Road        medium        large
19994     Approved      OHM Cycles         Road        medium       medium
19995     Approved      OHM Cycles     Standard          high       medium
19996     Approved           Solex         Road        medium       medium
19997     Approved      OHM Cycles     Standard        medium       medium
19998     Approved      OHM Cycles     Standard          high       medium
19999     Approved   Trek Bicycles     Standard        medium        small

       list_price  standard_cost  product_first_sold_date
0           71.49          53.62                  41245.0
1         2091.47         388.92                  41701.0
2         1793.43         248.82                  36361.0
3         1198.46         381.10                  36145.0
4         1765.30         709.48                  42226.0
5         1538.99         829.65                  39031.0
6           60.34          45.26                  34165.0
7         1292.84          13.44                  39915.0
8         1071.23         380.74                  33455.0
9         1231.15         161.60                  38216.0
10         574.64         459.71                  40784.0
11          71.16          56.93                  42172.0
12        1057.51         154.40                  34527.0
13        1661.92        1479.11                  34586.0
14        1765.30         709.48                  38193.0
15        2091.47         388.92                  37873.0
16        1555.58         818.01                  38206.0
17        1311.44        1167.18                  33888.0
18        1292.84          13.44                  39915.0
19        1538.99         829.65                  37337.0
20         499.53         388.72                  36334.0
21        1793.43         248.82                  36361.0
22        1793.43         248.82                  42145.0
23        1538.99         829.65                  42404.0
24        1362.99          57.74                  34079.0
25        1469.44         596.55                  42145.0
26        1469.44         596.55                  41047.0
27         574.64         459.71                  42560.0
28         360.40         270.30                  42710.0
29         642.31         513.85                  41922.0
...           ...            ...                      ...
19970     1403.50         954.82                  41245.0
19971     1289.85          74.51                  37220.0
19972     1812.75         582.48                  38750.0
19973     1073.07         933.84                  33429.0
19974     1661.92        1479.11                  34527.0
19975     1403.50         954.82                  42688.0
19976     1769.64         108.76                  38750.0
19977     1890.39         260.14                  33259.0
19978      499.53         388.72                  37698.0
19979      748.17         448.90                  37337.0
19980      569.56         528.43                  37874.0
19981     1703.52        1516.13                  40649.0
19982     1274.93         764.96                  39298.0
19983     1469.44         596.55                  41047.0
19984      230.91         173.18                  34527.0
19985      945.04         507.58                  39526.0
19986     1577.53         826.51                  40618.0
19987      544.05         376.84                  42105.0
19988      363.01         290.41                  37626.0
19989     1894.19         598.76                  37823.0
19990     1765.30         709.48                  42218.0
19991     1274.93         764.96                  39298.0
19992     1163.89         589.27                  39880.0
19993     1240.31         795.10                  40553.0
19994      742.54         667.40                  38216.0
19995     2005.66        1203.40                  37823.0
19996      416.98         312.74                  35560.0
19997     1636.90          44.71                  40410.0
19998      227.88         136.73                  38216.0
19999     1775.81        1580.47                  36334.0

[20000 rows x 13 columns]

In [3]:
NewCust = pd.read_excel (r'KPMG.xlsx', sheet_name='NewCustomerList')
print (NewCust)

    first_name     last_name  gender  past_3_years_bike_related_purchases  \
0      Chickie       Brister    Male                                   86
1        Morly        Genery    Male                                   69
2      Ardelis     Forrester  Female                                   10
3       Lucine         Stutt  Female                                   64
4      Melinda        Hadlee  Female                                   34
5        Druci       Brandli  Female                                   39
6     Rutledge         Hallt    Male                                   23
7       Nancie          Vian  Female                                   74
8         Duff     Karlowicz    Male                                   50
9      Barthel        Docket    Male                                   72
10    Rockwell        Matson    Male                                   94
11     Wheeler       Winward    Male                                   48
12        Olag           NaN    Male                                   60
13       Melba      Spellacy  Female                                   38
14      Mandie        Feares  Female                                   32
15       Dukie         Swire    Male                                   88
16    Marcelia     Monkleigh  Female                                   61
17   Winnifred  Beswetherick  Female                                   83
18      Odilia         Quick  Female                                   65
19       Karly     Willavize  Female                                    2
20      Teddie      Burchill    Male                                   11
21      Gaston     Dallaghan    Male                                   44
22        Otis         Ottey    Male                                   26
23    Tabbatha       Averill  Female                                    5
24       Brena     Schnitter  Female                                   78
25      Rourke      Gillbard    Male                                   11
26       Dyane       Burwell  Female                                   19
27    Claudine      Barstowk  Female                                   71
28     Blinnie          Roze  Female                                   84
29       Rhona     De Freyne  Female                                   45
..         ...           ...     ...                                  ...
970      Mavra         Finan  Female                                   30
971     Frieda       Tavinor  Female                                   43
972    Ellwood        Budden    Male                                   82
973       Alex      Patshull  Female                                   37
974    Aundrea      Outridge  Female                                   77
975       Amby        Bodega    Male                                   63
976       Esme      Pilipets    Male                                   15
977    Beverly       Domnick  Female                                   56
978    Artemis       Swanson    Male                                   77
979     Daryle     Marginson    Male                                   93
980       Tyne       Anshell  Female                                   71
981      Leona      Shorrock  Female                                   83
982  Bertrando        Carass    Male                                   45
983    Augusta         Munns  Female                                    5
984    Pauline      Dallosso       U                                   82
985   Lauralee         Fudge  Female                                   83
986   Consalve        Ballay    Male                                   41
987      Lolly        Prewer  Female                                   44
988       Vyky          Pegg  Female                                   64
989     Kellen      Pawelski  Female                                   83
990   Jermaine      Bagshawe  Female                                   60
991      Bryan       Jachtym    Male                                   59
992      Renie       Laundon  Female                                   32
993     Weidar     Etheridge    Male                                   38
994      Datha      Fishburn  Female                                   15
995  Ferdinand     Romanetti    Male                                   60
996       Burk       Wortley    Male                                   22
997   Melloney         Temby  Female                                   17
998     Dickie       Cubbini    Male                                   30
999      Sylas       Duffill    Male                                   56

           DOB                     job_title job_industry_category  \
0   1957-07-12               General Manager         Manufacturing
1   1970-03-22           Structural Engineer              Property
2   1974-08-28        Senior Cost Accountant    Financial Services
3   1979-01-28    Account Representative III         Manufacturing
4   1965-09-21             Financial Analyst    Financial Services
5   1951-04-29       Assistant Media Planner         Entertainment
6   1976-10-06          Compensation Analyst    Financial Services
7   1972-12-27  Human Resources Assistant II                Retail
8   1972-04-28            Speech Pathologist         Manufacturing
9   1985-08-02       Accounting Assistant IV                    IT
10  1995-01-01          Programmer Analyst I                Retail
11  1999-08-30      Environmental Specialist         Manufacturing
12  1990-05-13       Human Resources Manager    Telecommunications
13  1976-12-09                  VP Marketing                Health
14  1964-04-19           Clinical Specialist                Health
15  1954-03-31                           NaN         Manufacturing
16  1993-08-22           Associate Professor         Manufacturing
17  1976-06-08                       Actuary    Financial Services
18  1938-11-09               General Manager         Manufacturing
19  1954-08-12              Internal Auditor         Manufacturing
20  1968-12-21                  Programmer I         Manufacturing
21  1993-09-29             Financial Analyst    Financial Services
22  1998-02-05              Quality Engineer                   NaN
23  1977-12-17    Quality Control Specialist                   NaN
24  1982-10-11             Account Executive         Manufacturing
25  1945-08-03                           NaN              Property
26  1952-06-27                   Engineer II                Retail
27  1966-07-20                         Nurse              Property
28  1960-12-10                     Librarian         Entertainment
29  1960-11-22                           NaN                Health
..         ...                           ...                   ...
970 1967-08-23                         Nurse              Property
971 1999-03-04                           NaN                   NaN
972 1998-06-03                           NaN                Health
973 1966-01-02       Senior Quality Engineer                Retail
974 2001-01-24           Structural Engineer    Financial Services
975 1968-06-12                     Recruiter                   NaN
976 1967-05-06            Environmental Tech                Health
977 1938-12-10  Structural Analysis Engineer                    IT
978 1977-02-12               Web Designer II           Argiculture
979 1986-06-27            Environmental Tech           Argiculture
980 1992-04-08   Mechanical Systems Engineer                   NaN
981 1951-08-23       Senior Quality Engineer    Financial Services
982 1956-06-25               Sales Associate              Property
983 1951-09-17    Quality Control Specialist                   NaN
984        NaT    Desktop Support Technician                    IT
985 1987-09-21                Research Nurse                Health
986 1959-09-18               Web Developer I                    IT
987 1997-10-23                   Geologist I                Health
988 1943-03-15    Quality Control Specialist         Manufacturing
989 1945-07-26                           NaN         Manufacturing
990 1954-05-14            Help Desk Operator              Property
991 1974-05-15       Automation Specialist I         Manufacturing
992 1973-12-18       Assistant Media Planner         Entertainment
993 1959-07-13          Compensation Analyst    Financial Services
994 1990-07-02           Office Assistant IV                Retail
995 1959-10-07                     Paralegal    Financial Services
996 2001-10-17        Senior Sales Associate                Health
997 1954-10-05  Budget/Accounting Analyst IV    Financial Services
998 1952-12-17             Financial Advisor    Financial Services
999 1955-10-02           Staff Accountant IV              Property

        wealth_segment deceased_indicator owns_car  ...  state    country  \
0        Mass Customer                  N      Yes  ...    QLD  Australia
1        Mass Customer                  N       No  ...    NSW  Australia
2    Affluent Customer                  N       No  ...    VIC  Australia
3    Affluent Customer                  N      Yes  ...    QLD  Australia
4    Affluent Customer                  N       No  ...    NSW  Australia
5       High Net Worth                  N      Yes  ...    QLD  Australia
6        Mass Customer                  N       No  ...    NSW  Australia
7        Mass Customer                  N      Yes  ...    QLD  Australia
8        Mass Customer                  N      Yes  ...    NSW  Australia
9        Mass Customer                  N      Yes  ...    QLD  Australia
10      High Net Worth                  N       No  ...    QLD  Australia
11       Mass Customer                  N       No  ...    VIC  Australia
12       Mass Customer                  N       No  ...    NSW  Australia
13       Mass Customer                  N       No  ...    NSW  Australia
14       Mass Customer                  N       No  ...    QLD  Australia
15   Affluent Customer                  N      Yes  ...    NSW  Australia
16       Mass Customer                  N      Yes  ...    QLD  Australia
17       Mass Customer                  N       No  ...    VIC  Australia
18   Affluent Customer                  N      Yes  ...    NSW  Australia
19      High Net Worth                  N       No  ...    NSW  Australia
20       Mass Customer                  N      Yes  ...    NSW  Australia
21       Mass Customer                  N      Yes  ...    NSW  Australia
22       Mass Customer                  N       No  ...    QLD  Australia
23   Affluent Customer                  N      Yes  ...    NSW  Australia
24       Mass Customer                  N       No  ...    QLD  Australia
25       Mass Customer                  N       No  ...    QLD  Australia
26       Mass Customer                  N      Yes  ...    NSW  Australia
27      High Net Worth                  N      Yes  ...    QLD  Australia
28      High Net Worth                  N       No  ...    QLD  Australia
29      High Net Worth                  N       No  ...    VIC  Australia
..                 ...                ...      ...  ...    ...        ...
970  Affluent Customer                  N      Yes  ...    NSW  Australia
971  Affluent Customer                  N       No  ...    VIC  Australia
972      Mass Customer                  N      Yes  ...    NSW  Australia
973      Mass Customer                  N      Yes  ...    QLD  Australia
974  Affluent Customer                  N      Yes  ...    VIC  Australia
975  Affluent Customer                  N      Yes  ...    VIC  Australia
976      Mass Customer                  N      Yes  ...    VIC  Australia
977      Mass Customer                  N       No  ...    NSW  Australia
978      Mass Customer                  N      Yes  ...    VIC  Australia
979      Mass Customer                  N      Yes  ...    NSW  Australia
980      Mass Customer                  N      Yes  ...    NSW  Australia
981  Affluent Customer                  N      Yes  ...    QLD  Australia
982      Mass Customer                  N       No  ...    NSW  Australia
983      Mass Customer                  N       No  ...    NSW  Australia
984  Affluent Customer                  N      Yes  ...    NSW  Australia
985      Mass Customer                  N       No  ...    VIC  Australia
986      Mass Customer                  N      Yes  ...    NSW  Australia
987      Mass Customer                  N       No  ...    NSW  Australia
988      Mass Customer                  N      Yes  ...    NSW  Australia
989     High Net Worth                  N      Yes  ...    NSW  Australia
990      Mass Customer                  N      Yes  ...    QLD  Australia
991      Mass Customer                  N      Yes  ...    VIC  Australia
992      Mass Customer                  N      Yes  ...    QLD  Australia
993      Mass Customer                  N      Yes  ...    NSW  Australia
994      Mass Customer                  N       No  ...    VIC  Australia
995  Affluent Customer                  N       No  ...    NSW  Australia
996      Mass Customer                  N       No  ...    NSW  Australia
997  Affluent Customer                  N      Yes  ...    QLD  Australia
998      Mass Customer                  N      Yes  ...    QLD  Australia
999      Mass Customer                  N      Yes  ...    NSW  Australia

     property_valuation Unnamed: 16 Unnamed: 17  Unnamed: 18  Unnamed: 19  \
0                     6        0.87      1.0875     1.359375     1.155469
1                    11        0.69      0.6900     0.862500     0.733125
2                     5        0.69      0.6900     0.690000     0.690000
3                     1        0.45      0.5625     0.562500     0.562500
4                     9        0.64      0.6400     0.800000     0.800000
5                     7        0.55      0.6875     0.687500     0.687500
6                     7        0.98      0.9800     0.980000     0.833000
7                     5        0.89      1.1125     1.112500     0.945625
8                    10        0.41      0.5125     0.640625     0.544531
9                     5        0.40      0.5000     0.500000     0.425000
10                    6        0.93      0.9300     1.162500     1.162500
11                    8        0.61      0.6100     0.610000     0.518500
12                   11        0.62      0.6200     0.775000     0.658750
13                   10        1.05      1.0500     1.312500     1.115625
14                    8        0.85      0.8500     0.850000     0.722500
15                    8        0.44      0.5500     0.687500     0.687500
16                    6        0.44      0.5500     0.550000     0.467500
17                   10        1.06      1.0600     1.325000     1.126250
18                   11        0.91      1.1375     1.421875     1.421875
19                   10        0.92      0.9200     1.150000     1.150000
20                    9        0.94      1.1750     1.468750     1.248437
21                    7        0.78      0.9750     0.975000     0.828750
22                    4        1.00      1.0000     1.000000     0.850000
23                    8        0.72      0.9000     0.900000     0.900000
24                    5        0.62      0.6200     0.620000     0.527000
25                    4        0.75      0.7500     0.750000     0.637500
26                    2        0.57      0.7125     0.712500     0.605625
27                   11        0.49      0.6125     0.765625     0.765625
28                    7        1.05      1.0500     1.312500     1.312500
29                   10        0.78      0.7800     0.975000     0.975000
..                  ...         ...         ...          ...          ...
970                   9        0.55      0.6875     0.859375     0.859375
971                   6        0.53      0.5300     0.530000     0.530000
972                  10        0.64      0.8000     1.000000     0.850000
973                   5        0.64      0.8000     0.800000     0.680000
974                  12        0.62      0.7750     0.968750     0.968750
975                   6        1.05      1.3125     1.312500     1.312500
976                   9        0.75      0.9375     1.171875     0.996094
977                  10        1.09      1.0900     1.362500     1.158125
978                   5        1.02      1.2750     1.275000     1.083750
979                  12        0.52      0.6500     0.812500     0.690625
980                   8        0.75      0.9375     0.937500     0.796875
981                   1        0.42      0.5250     0.656250     0.656250
982                   5        1.08      1.0800     1.080000     0.918000
983                  11        0.97      0.9700     1.212500     1.030625
984                  10        0.77      0.9625     1.203125     1.203125
985                   4        0.90      0.9000     1.125000     0.956250
986                   8        1.01      1.2625     1.262500     1.073125
987                   7        0.56      0.5600     0.560000     0.476000
988                   7        0.96      1.2000     1.200000     1.020000
989                   8        0.91      1.1375     1.421875     1.421875
990                   6        1.10      1.3750     1.375000     1.168750
991                   3        0.53      0.6625     0.662500     0.563125
992                   3        1.03      1.2875     1.287500     1.094375
993                   4        0.59      0.7375     0.737500     0.626875
994                  12        0.67      0.6700     0.837500     0.711875
995                   7        0.43      0.4300     0.430000     0.430000
996                  10        0.53      0.5300     0.662500     0.563125
997                   2        0.61      0.7625     0.762500     0.762500
998                   2        1.07      1.3375     1.337500     1.136875
999                   9        0.51      0.6375     0.796875     0.677344

     Unnamed: 20  Rank     Value
0              1     1  1.718750
1              1     1  1.718750
2              1     1  1.718750
3              4     4  1.703125
4              4     4  1.703125
5              6     6  1.671875
6              6     6  1.671875
7              8     8  1.656250
8              8     8  1.656250
9             10    10  1.640625
10            10    10  1.640625
11            12    12  1.625000
12            13    13  1.609375
13            14    14  1.593750
14            14    14  1.593750
15            16    16  1.562500
16            17    17  1.546875
17            17    17  1.546875
18            19    19  1.531250
19            19    19  1.531250
20            21    21  1.515625
21            21    21  1.515625
22            23    23  1.500000
23            23    23  1.500000
24            25    25  1.484375
25            26    26  1.468750
26            26    26  1.468750
27            26    26  1.468750
28            26    26  1.468750
29            30    30  1.460938
..           ...   ...       ...
970          967   967  0.435625
971          972   972  0.430000
972          972   972  0.430000
973          974   974  0.425000
974          974   974  0.425000
975          974   974  0.425000
976          977   977  0.420000
977          977   977  0.420000
978          979   979  0.416500
979          979   979  0.416500
980          979   979  0.416500
981          979   979  0.416500
982          983   983  0.410000
983          983   983  0.410000
984          985   985  0.408000
985          985   985  0.408000
986          987   987  0.400000
987          988   988  0.399500
988          988   988  0.399500
989          988   988  0.399500
990          988   988  0.399500
991          988   988  0.399500
992          993   993  0.391000
993          994   994  0.382500
994          994   994  0.382500
995          996   996  0.374000
996          997   997  0.357000
997          997   997  0.357000
998          997   997  0.357000
999         1000  1000  0.340000


In [4]:
CustDemo = pd.read_excel (r'KPMG.xlsx', sheet_name='CustomerDemographic')
print (CustDemo)

      customer_id      first_name      last_name  gender  \
0               1         Laraine      Medendorp       F
1               2             Eli        Bockman    Male
2               3           Arlin         Dearle    Male
3               4          Talbot            NaN    Male
4               5  Sheila-kathryn         Calton  Female
5               6            Curr      Duckhouse    Male
6               7            Fina         Merali  Female
7               8             Rod          Inder    Male
8               9            Mala           Lind  Female
9              10        Fiorenze        Birdall  Female
10             11           Uriah         Bisatt    Male
11             12         Sawyere       Flattman    Male
12             13        Gabriele       Norcross    Male
13             14        Rayshell       Kitteman  Female
14             15          Erroll         Radage    Male
15             16          Harlin           Parr    Male
16             17           Heath        Faraday    Male
17             18          Marjie        Neasham  Female
18             19          Sorcha         Keyson  Female
19             20          Basile          Firth    Male
20             21            Mile       Cammocke    Male
21             22         Deeanne       Durtnell  Female
22             23            Olav          Polak    Male
23             24             Kim         Skpsey  Female
24             25           Geoff          Assaf    Male
25             26           Trixi       Ginnelly  Female
26             27          Garvin          Klees    Male
27             28             Fee        Zellmer    Male
28             29            Mona       Sancraft  Female
29             30         Darrick      Helleckas    Male
...           ...             ...            ...     ...
3970         3971         Analise         Asbrey  Female
3971         3972       Maribelle       Schaffel  Female
3972         3973         Carolan          Jorez  Female
3973         3974           Misha        Ranklin  Female
3974         3975      Dianemarie        Kidgell  Female
3975         3976          Gretel       Chrystal  Female
3976         3977        Katrinka  Van der Beken  Female
3977         3978         Kathlin         Robker  Female
3978         3979           Kleon           Adam    Male
3979         3980            Nils      McGebenay    Male
3980         3981       Konstance          Draye  Female
3981         3982         Maurita       O'Kinedy  Female
3982         3983          Jarred          Lyste    Male
3983         3984         Thadeus         Buxsey    Male
3984         3985           Caryn        Padbury  Female
3985         3986          Oralle       Petrello  Female
3986         3987          Beckie        Wakeham  Female
3987         3988       Ammamaria       Ashburne  Female
3988         3989         Nicolas        Burdass    Male
3989         3990         Reynard         Hagger    Male
3990         3991           Rolph       Sweetnam    Male
3991         3992         Germain        Tireman    Male
3992         3993            Andi        Dumelow  Female
3993         3994         Stephie          Byars  Female
3994         3995           Rusty         Iapico    Male
3995         3996         Rosalia       Halgarth  Female
3996         3997          Blanch         Nisuis  Female
3997         3998          Sarene        Woolley       U
3998         3999       Patrizius            NaN    Male
3999         4000           Kippy        Oldland    Male

      past_3_years_bike_related_purchases        DOB  \
0                                      93 1953-10-12
1                                      81 1980-12-16
2                                      61 1954-01-20
3                                      33 1961-10-03
4                                      56 1977-05-13
5                                      35 1966-09-16
6                                       6 1976-02-23
7                                      31 1962-03-30
8                                      97 1973-03-10
9                                      49 1988-10-11
10                                     99 1954-04-30
11                                     58 1994-07-21
12                                     38 1955-02-15
13                                     85 1983-03-25
14                                     91 2000-07-13
15                                     38 1977-02-27
16                                     57 1962-03-19
17                                     79 1967-07-06
18                                     76 2001-04-15
19                                     72 1980-08-13
20                                     74 1980-09-20
21                                     79 1962-12-10
22                                     43 1995-02-10
23                                     55 1977-12-03
24                                     72 1976-12-02
25                                     12 1978-06-10
26                                     37 1978-09-25
27                                      5 1973-09-30
28                                     62 1968-06-22
29                                     18 1961-10-18
...                                   ...        ...
3970                                    2 1979-01-14
3971                                    6 1979-03-28
3972                                   24 1963-07-13
3973                                   82 1961-02-11
3974                                    2 1971-08-11
3975                                    0 1957-11-20
3976                                   31 1965-08-21
3977                                    4 1972-03-02
3978                                   67 1974-07-13
3979                                   41 1964-01-16
3980                                   34 1994-09-10
3981                                   89 1962-06-02
3982                                   19 1965-04-21
3983                                   74 1960-02-16
3984                                   44 1998-06-21
3985                                    1 1976-12-01
3986                                   18 1964-05-29
3987                                   97 1994-07-14
3988                                   75 1999-06-23
3989                                   99 1998-03-05
3990                                   61 1985-08-06
3991                                   99 1980-04-02
3992                                    6 1974-12-05
3993                                    5 1989-04-07
3994                                   93 1975-12-12
3995                                    8 1975-08-09
3996                                   87 2001-07-13
3997                                   60        NaT
3998                                   11 1973-10-24
3999                                   76 1991-11-05

                                 job_title job_industry_category  \
0                      Executive Secretary                Health
1                   Administrative Officer    Financial Services
2                       Recruiting Manager              Property
3                                      NaN                    IT
4                            Senior Editor                   NaN
5                                      NaN                Retail
6                                      NaN    Financial Services
7                          Media Manager I                   NaN
8     Business Systems Development Analyst           Argiculture
9                  Senior Quality Engineer    Financial Services
10                                     NaN              Property
11                  Nuclear Power Engineer         Manufacturing
12                             Developer I    Financial Services
13                       Account Executive    Financial Services
14                        Junior Executive         Manufacturing
15                        Media Manager IV                   NaN
16                         Sales Associate                   NaN
17                               Professor                   NaN
18                     Geological Engineer         Manufacturing
19                         Project Manager         Manufacturing
20                     Safety Technician I         Manufacturing
21                                     NaN                    IT
22                                     NaN                   NaN
23                    Research Assistant I           Argiculture
24                Accounting Assistant III    Financial Services
25                                  Editor    Financial Services
26                          Research Nurse                Health
27                 Senior Quality Engineer                Health
28                   Safety Technician III         Manufacturing
29                                     NaN                    IT
...                                    ...                   ...
3970            Desktop Support Technician    Financial Services
3971                                   NaN                Retail
3972                                Editor         Manufacturing
3973                      Technical Writer                   NaN
3974            Administrative Assistant I         Entertainment
3975                      Internal Auditor                   NaN
3976                    Biostatistician II         Manufacturing
3977                          Developer II    Financial Services
3978                                   NaN    Financial Services
3979                        Web Designer I         Manufacturing
3980            Quality Control Specialist                Health
3981                       General Manager         Manufacturing
3982                      Graphic Designer                   NaN
3983                             Librarian         Entertainment
3984                      Web Developer IV              Property
3985                         Social Worker                Health
3986                                   NaN           Argiculture
3987              Automation Specialist IV                Health
3988              Environmental Specialist           Argiculture
3989            Desktop Support Technician                Health
3990                 Chief Design Engineer         Manufacturing
3991             Database Administrator IV         Manufacturing
3992                             Librarian         Entertainment
3993          Structural Analysis Engineer         Manufacturing
3994                       Staff Scientist         Manufacturing
3995                 VP Product Management                Health
3996                       Statistician II         Manufacturing
3997                     Assistant Manager                    IT
3998                                   NaN         Manufacturing
3999                  Software Engineer IV                   NaN

         wealth_segment deceased_indicator  \
0         Mass Customer                  N
1         Mass Customer                  N
2         Mass Customer                  N
3         Mass Customer                  N
4     Affluent Customer                  N
5        High Net Worth                  N
6     Affluent Customer                  N
7         Mass Customer                  N
8     Affluent Customer                  N
9         Mass Customer                  N
10        Mass Customer                  N
11        Mass Customer                  N
12       High Net Worth                  N
13    Affluent Customer                  N
14        Mass Customer                  N
15        Mass Customer                  N
16    Affluent Customer                  N
17    Affluent Customer                  N
18       High Net Worth                  N
19        Mass Customer                  N
20    Affluent Customer                  N
21        Mass Customer                  N
22       High Net Worth                  N
23        Mass Customer                  N
24        Mass Customer                  N
25        Mass Customer                  N
26        Mass Customer                  N
27    Affluent Customer                  N
28        Mass Customer                  N
29    Affluent Customer                  N
...                 ...                ...
3970     High Net Worth                  N
3971      Mass Customer                  N
3972     High Net Worth                  N
3973  Affluent Customer                  N
3974  Affluent Customer                  N
3975  Affluent Customer                  N
3976      Mass Customer                  N
3977      Mass Customer                  N
3978      Mass Customer                  N
3979      Mass Customer                  N
3980      Mass Customer                  N
3981      Mass Customer                  N
3982      Mass Customer                  N
3983  Affluent Customer                  N
3984      Mass Customer                  N
3985      Mass Customer                  N
3986      Mass Customer                  N
3987      Mass Customer                  N
3988  Affluent Customer                  N
3989     High Net Worth                  N
3990      Mass Customer                  N
3991  Affluent Customer                  N
3992      Mass Customer                  N
3993  Affluent Customer                  N
3994      Mass Customer                  N
3995      Mass Customer                  N
3996     High Net Worth                  N
3997     High Net Worth                  N
3998  Affluent Customer                  N
3999  Affluent Customer                  N

                                                default owns_car  tenure
0                                                    "'      Yes    11.0
1                          <script>alert('hi')</script>      Yes    16.0
2                                   2018-02-01 00:00:00      Yes    15.0
3     () { _; } >_[$($())] { touch /tmp/blns.shellsh...       No     7.0
4                                                   NIL      Yes     8.0
5                                              ðµ ð ð ð      Yes    13.0
6                                             â°â´âµâââ      Yes    11.0
7                               (â¯Â°â¡Â°ï¼â¯ï¸µ â»ââ»)       No     7.0
8                                                   0/0      Yes     8.0
9                                                  ð©ð½      Yes    20.0
10                                   ÅâÂ´Â®â Â¥Â¨ËÃ¸Ïââ       No     9.0
11                                                  nil       No     8.0
12                                                 -100      Yes     8.0
13                                               â°â´âµ       No     6.0
14                                                    ð       No     1.0
15    1000000000000000049861653971908893017010268485...      Yes    18.0
16                     ï¾ï½¥â¿ã¾â²(ï½¡ââ¿âï½¡)â±â¿ï½¥ï¾      Yes    15.0
17                                    Î©âÃ§ââ«ËÂµâ¤â¥Ã·       No    11.0
18                                      ÅâÂ´â°ËÃÂ¨ËÃâââ       No     1.0
19                                                 ð©ð½       No    11.0
20                                                 -100      Yes    16.0
21                                               ï¼ï¼ï¼       No    11.0
22                                  2018-02-01 00:00:00      Yes     1.0
23           ../../../../../../../../../../../etc/hosts      Yes    15.0
24               ×Ö¸×Ö°×ªÖ¸×testØ§ÙØµÙØ­Ø§Øª Ø§ÙØªÙØ­ÙÙ      Yes    21.0
25                                           <>?:"{}|_+      Yes    16.0
26                                                ''''"      Yes    12.0
27                                           ,./;'[]\-=      Yes    21.0
28         () { 0; }; touch /tmp/blns.shellshock1.fail;       No    19.0
29                                   ì¬íê³¼íì ì´íì°êµ¬ì      Yes     6.0
...                                                 ...      ...     ...
3970                                                NaN       No    16.0
3971  Ì¦HÍÌ¬Ì¤ÌÌ¤eÍ ÍÌÌ¥ÌÌ»ÍÌwÌhÌÌ¯ÍoÌÍÌÍÌ±Ì® ÒÌºÌÌÌ...       No     8.0
3972                                  ð¾ ð ð ð ð ð ð ð§       No    17.0
3973                                                  1      Yes     9.0
3974                                                NIL       No    18.0
3975                                            '"''''"      Yes    13.0
3976                                 ÅâÂ´Â®â Â¥Â¨ËÃ¸Ïââ      Yes    16.0
3977                                                NIL       No     5.0
3978                   â¤ï¸ ð ð ð ð ð ð ð ð ð ð ð ð ð ð      Yes    18.0
3979                                                 â¡       No    12.0
3980  ËÉnbá´lÉ ÉuÆÉÉ¯ ÇÉ¹olop ÊÇ ÇÉ¹oqÉl Ên Êunpá´pá...       No     1.0
3981                                                  1      Yes    12.0
3982  Ì¦HÍÌ¬Ì¤ÌÌ¤eÍ ÍÌÌ¥ÌÌ»ÍÌwÌhÌÌ¯ÍoÌÍÌÍÌ±Ì® ÒÌºÌÌÌ...      Yes     9.0
3983                           âð¿ ðªð¿ ðð¿ ðð¿ ðð¿ ðð¿       No    10.0
3984                                                0/0       No     4.0
3985                                                NaN       No    21.0
3986                                                  á       No     7.0
3987                                                 â¡      Yes     1.0
3988                                                âââ      Yes     1.0
3989                                                  0       No     1.0
3990                                                 "'      Yes    13.0
3991  Ø«Ù ÙÙØ³ Ø³ÙØ·Øª ÙØ¨Ø§ÙØªØ­Ø¯ÙØ¯Ø, Ø¬Ø²ÙØ±ØªÙ ...      Yes    18.0
3992                                                 á        No    10.0
3993                                               -100       No    12.0
3994                                                 á       Yes    14.0
3995                                               -100       No    19.0
3996                                           â¦testâ§      Yes     1.0
3997                                                NaN       No     NaN
3998                             Â¡â¢Â£Â¢âÂ§Â¶â¢ÂªÂºââ       Yes    10.0
3999                                                0/0       No    11.0

[4000 rows x 13 columns]

In [5]:
CustAdd = pd.read_excel (r'KPMG.xlsx', sheet_name='CustomerAddress')
print (CustAdd)

      customer_id                     address  postcode            state  \
0               1          060 Morning Avenue      2016  New South Wales
1               2         6 Meadow Vale Court      2153  New South Wales
2               4          0 Holy Cross Court      4211              QLD
3               5         17979 Del Mar Point      2448  New South Wales
4               6            9 Oakridge Court      3216              VIC
5               7            4 Delaware Trail      2210  New South Wales
6               8         49 Londonderry Lane      2650  New South Wales
7               9             97736 7th Trail      2023  New South Wales
8              11        93405 Ludington Park      3044              VIC
9              12     44339 Golden Leaf Alley      4557              QLD
10             13         2 Sutherland Street      3799              VIC
11             14             9 Mcbride Trail      2760  New South Wales
12             15      9861 New Castle Avenue      2428  New South Wales
13             16            52 Moland Street      3331              VIC
14             17       82391 Kensington Lane      3058              VIC
15             18               092 2nd Alley      2135  New South Wales
16             19           59 Spaight Circle      2233  New South Wales
17             20        032 Bartelt Crossing      2444  New South Wales
18             21             18 Jenna Center      2650  New South Wales
19             24            3 Cordelia Plaza      2153  New South Wales
20             25               28 5th Center      4413              QLD
21             26              52 Carey Alley      4740              QLD
22             27              96 Texas Plaza      3218              VIC
23             28             48 Eagan Avenue      4868              QLD
24             29                9 Buell Park      4116              QLD
25             30         02663 Buell Parkway      2519  New South Wales
26             31         2294 Pleasure Place      2135  New South Wales
27             32         2951 Petterle Place      2756  New South Wales
28             33             63 Lukken Drive      2170  New South Wales
29             34              833 Luster Way      4005              QLD
...           ...                         ...       ...              ...
3969         3974        81609 Vernon Terrace      3934              VIC
3970         3975             37 Hintze Court      2168              NSW
3971         3976            07 Morning Court      3805              VIC
3972         3977         327 Loeprich Street      3187              VIC
3973         3978       5106 Northridge Drive      2560              NSW
3974         3979  9754 High Crossing Terrace      2148              NSW
3975         3980         7 Meadow Vale Court      2114              NSW
3976         3981          80260 Morning Road      3178              VIC
3977         3982     38017 Briar Crest Drive      2165              NSW
3978         3983       60 Morningstar Center      2126              NSW
3979         3984         218 Stuart Junction      2223              NSW
3980         3985          9 Butterfield Lane      4077              QLD
3981         3986        614 Burning Wood Way      2148              NSW
3982         3987              9 Grover Point      4218              QLD
3983         3988            565 Bunting Park      2076              NSW
3984         3989       9461 Saint Paul Trail      2428              NSW
3985         3990          5204 Delaware Pass      2560              NSW
3986         3991               24 Scott Pass      4300              QLD
3987         3992             8 Randy Parkway      2209              NSW
3988         3993           681 Elmside Place      3750              VIC
3989         3994      2918 Summer Ridge Hill      3030              VIC
3990         3995               613 Erie Lane      2088              NSW
3991         3996          0 Transport Center      3977              VIC
3992         3997         4 Dovetail Crossing      2350              NSW
3993         3998        736 Roxbury Junction      2540              NSW
3994         3999             1482 Hauk Trail      3064              VIC
3995         4000   57042 Village Green Point      4511              QLD
3996         4001      87 Crescent Oaks Alley      2756              NSW
3997         4002            8194 Lien Street      4032              QLD
3998         4003             320 Acker Drive      2251              NSW

        country  property_valuation
0     Australia                  10
1     Australia                  10
2     Australia                   9
3     Australia                   4
4     Australia                   9
5     Australia                   9
6     Australia                   4
7     Australia                  12
8     Australia                   8
9     Australia                   4
10    Australia                   6
11    Australia                   8
12    Australia                   9
13    Australia                   4
14    Australia                   9
15    Australia                  12
16    Australia                   9
17    Australia                   8
18    Australia                   7
19    Australia                  10
20    Australia                   3
21    Australia                   5
22    Australia                   7
23    Australia                   4
24    Australia                   7
25    Australia                  11
26    Australia                  12
27    Australia                   9
28    Australia                   9
29    Australia                   8
...         ...                 ...
3969  Australia                   8
3970  Australia                   9
3971  Australia                   7
3972  Australia                  11
3973  Australia                   7
3974  Australia                   8
3975  Australia                  10
3976  Australia                   9
3977  Australia                   9
3978  Australia                  10
3979  Australia                  10
3980  Australia                   5
3981  Australia                   9
3982  Australia                  10
3983  Australia                  11
3984  Australia                   2
3985  Australia                   8
3986  Australia                   5
3987  Australia                  11
3988  Australia                   6
3989  Australia                   2
3990  Australia                  12
3991  Australia                   6
3992  Australia                   2
3993  Australia                   6
3994  Australia                   3
3995  Australia                   6
3996  Australia                  10
3997  Australia                   7
3998  Australia                   7

[3999 rows x 6 columns]

In [3]:
df

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date
0,1,2,2950,2017-02-25,0.0,Approved,Solex,Standard,medium,medium,71.49,53.62,41245.0
1,2,3,3120,2017-05-21,1.0,Approved,Trek Bicycles,Standard,medium,large,2091.47,388.92,41701.0
2,3,37,402,2017-10-16,0.0,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82,36361.0
3,4,88,3135,2017-08-31,0.0,Approved,Norco Bicycles,Standard,medium,medium,1198.46,381.10,36145.0
4,5,78,787,2017-10-01,1.0,Approved,Giant Bicycles,Standard,medium,large,1765.30,709.48,42226.0
5,6,25,2339,2017-03-08,1.0,Approved,Giant Bicycles,Road,medium,medium,1538.99,829.65,39031.0
6,7,22,1542,2017-04-21,1.0,Approved,WeareA2B,Standard,medium,medium,60.34,45.26,34165.0
7,8,15,2459,2017-07-15,0.0,Approved,WeareA2B,Standard,medium,medium,1292.84,13.44,39915.0
8,9,67,1305,2017-08-10,0.0,Approved,Solex,Standard,medium,large,1071.23,380.74,33455.0
9,10,12,3262,2017-08-30,1.0,Approved,WeareA2B,Standard,medium,medium,1231.15,161.60,38216.0
10,11,5,1986,2017-01-17,0.0,Approved,Trek Bicycles,Mountain,low,medium,574.64,459.71,40784.0
11,12,61,2783,2017-01-05,1.0,Approved,OHM Cycles,Standard,low,medium,71.16,56.93,42172.0
12,13,35,1243,2017-02-26,1.0,Approved,Trek Bicycles,Standard,low,medium,1057.51,154.40,34527.0
13,14,16,2717,2017-09-10,0.0,Approved,Norco Bicycles,Standard,high,small,1661.92,1479.11,34586.0
14,15,12,247,2017-06-11,0.0,Approved,Giant Bicycles,Standard,medium,large,1765.30,709.48,38193.0
15,16,3,2961,2017-10-10,0.0,Approved,Trek Bicycles,Standard,medium,large,2091.47,388.92,37873.0
16,17,79,2426,2017-04-03,0.0,Approved,Norco Bicycles,Standard,medium,medium,1555.58,818.01,38206.0
17,18,33,1842,2017-06-02,0.0,Approved,Giant Bicycles,Standard,medium,small,1311.44,1167.18,33888.0
18,19,54,2268,2017-04-06,1.0,Approved,WeareA2B,Standard,medium,medium,1292.84,13.44,39915.0
19,20,25,3002,2017-01-28,1.0,Approved,Giant Bicycles,Road,medium,medium,1538.99,829.65,37337.0
20,21,27,1582,2017-10-09,0.0,Approved,Trek Bicycles,Standard,medium,medium,499.53,388.72,36334.0
21,22,37,595,2017-06-29,1.0,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82,36361.0
22,23,37,2001,2017-04-08,1.0,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82,42145.0
23,24,82,515,2017-10-18,0.0,Approved,Giant Bicycles,Road,medium,medium,1538.99,829.65,42404.0
24,25,89,2822,2017-06-11,0.0,Approved,WeareA2B,Touring,medium,large,1362.99,57.74,34079.0
25,26,64,2596,2017-01-10,0.0,Approved,Trek Bicycles,Standard,medium,large,1469.44,596.55,42145.0
26,27,64,2666,2017-04-11,1.0,Approved,Trek Bicycles,Standard,medium,large,1469.44,596.55,41047.0
27,28,19,76,2017-12-23,0.0,Approved,Trek Bicycles,Mountain,low,medium,574.64,459.71,42560.0
28,29,72,3368,2017-10-13,1.0,Approved,Norco Bicycles,Standard,medium,medium,360.40,270.30,42710.0
29,30,91,1173,2017-03-15,0.0,Approved,WeareA2B,Standard,low,medium,642.31,513.85,41922.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19970,19971,1,1464,2017-03-18,0.0,Approved,Giant Bicycles,Standard,medium,medium,1403.50,954.82,41245.0
19971,19972,46,2967,2017-05-10,0.0,Approved,Solex,Standard,low,medium,1289.85,74.51,37220.0
19972,19973,39,1188,2017-05-13,1.0,Approved,Giant Bicycles,Standard,medium,large,1812.75,582.48,38750.0
19973,19974,80,148,2017-11-17,1.0,Approved,OHM Cycles,Touring,low,medium,1073.07,933.84,33429.0
19974,19975,88,3129,2017-09-08,1.0,Approved,Norco Bicycles,Standard,high,small,1661.92,1479.11,34527.0
19975,19976,35,1700,2017-10-22,0.0,Approved,Giant Bicycles,Standard,medium,medium,1403.50,954.82,42688.0
19976,19977,44,1102,2017-01-02,0.0,Approved,WeareA2B,Standard,medium,medium,1769.64,108.76,38750.0
19977,19978,57,932,2017-10-08,1.0,Approved,WeareA2B,Touring,medium,large,1890.39,260.14,33259.0
19978,19979,27,333,2017-12-08,1.0,Approved,Trek Bicycles,Standard,medium,medium,499.53,388.72,37698.0
19979,19980,30,1435,2017-03-04,1.0,Approved,Solex,Standard,high,medium,748.17,448.90,37337.0
19980,19981,95,3304,2017-06-07,0.0,Approved,Giant Bicycles,Standard,medium,large,569.56,528.43,37874.0
19981,19982,28,1075,2017-07-20,1.0,Approved,Solex,Road,medium,small,1703.52,1516.13,40649.0
19982,19983,11,1137,2017-03-11,1.0,Approved,Giant Bicycles,Standard,high,medium,1274.93,764.96,39298.0
19983,19984,80,275,2017-07-02,0.0,Approved,Trek Bicycles,Standard,medium,large,1469.44,596.55,41047.0
19984,19985,31,873,2017-11-15,1.0,Approved,Giant Bicycles,Standard,medium,medium,230.91,173.18,34527.0
19985,19986,36,2918,2017-11-09,1.0,Approved,Solex,Standard,low,medium,945.04,507.58,39526.0
19986,19987,38,2385,2017-11-01,0.0,Approved,Solex,Standard,medium,medium,1577.53,826.51,40618.0
19987,19988,0,13,2017-04-05,1.0,Approved,Norco Bicycles,Road,medium,medium,544.05,376.84,42105.0
19988,19989,0,714,2017-04-27,1.0,Approved,Norco Bicycles,Standard,low,medium,363.01,290.41,37626.0
19989,19990,55,135,2017-01-27,1.0,Cancelled,Trek Bicycles,Road,medium,large,1894.19,598.76,37823.0
19990,19991,78,425,2017-01-26,0.0,Approved,Giant Bicycles,Standard,medium,large,1765.30,709.48,42218.0
19991,19992,11,1374,2017-09-14,0.0,Approved,Giant Bicycles,Standard,high,medium,1274.93,764.96,39298.0
19992,19993,13,5,2017-04-28,0.0,Approved,Solex,Standard,medium,medium,1163.89,589.27,39880.0
19993,19994,77,2618,2017-12-23,0.0,Approved,Norco Bicycles,Road,medium,large,1240.31,795.10,40553.0
19994,19995,9,718,2017-05-13,1.0,Approved,OHM Cycles,Road,medium,medium,742.54,667.40,38216.0
19995,19996,51,1018,2017-06-24,1.0,Approved,OHM Cycles,Standard,high,medium,2005.66,1203.40,37823.0
19996,19997,41,127,2017-11-09,1.0,Approved,Solex,Road,medium,medium,416.98,312.74,35560.0
19997,19998,87,2284,2017-04-14,1.0,Approved,OHM Cycles,Standard,medium,medium,1636.90,44.71,40410.0
19998,19999,6,2764,2017-07-03,0.0,Approved,OHM Cycles,Standard,high,medium,227.88,136.73,38216.0
19999,20000,11,1144,2017-09-22,1.0,Approved,Trek Bicycles,Standard,medium,small,1775.81,1580.47,36334.0

In [4]:
df.describe()

,transaction_id,product_id,customer_id,online_order,list_price,standard_cost,product_first_sold_date
count,20000.000000,20000.00000,20000.000000,19640.000000,20000.000000,19803.000000,19803.000000
mean,10000.500000,45.36465,1738.246050,0.500458,1107.829449,556.046951,38199.776549
std,5773.647028,30.75359,1011.951046,0.500013,582.825242,405.955660,2875.201110
min,1.000000,0.00000,1.000000,0.000000,12.010000,7.210000,33259.000000
25%,5000.750000,18.00000,857.750000,0.000000,575.270000,215.140000,35667.000000
50%,10000.500000,44.00000,1736.000000,1.000000,1163.890000,507.580000,38216.000000
75%,15000.250000,72.00000,2613.000000,1.000000,1635.300000,795.100000,40672.000000
max,20000.000000,100.00000,5034.000000,1.000000,2091.470000,1759.850000,42710.000000

Missing Values for online order, standard cost, product_first_sold_Date

In [5]:
df.head(5)

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date
0,1,2,2950,2017-02-25,0.0,Approved,Solex,Standard,medium,medium,71.49,53.62,41245.0
1,2,3,3120,2017-05-21,1.0,Approved,Trek Bicycles,Standard,medium,large,2091.47,388.92,41701.0
2,3,37,402,2017-10-16,0.0,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82,36361.0
3,4,88,3135,2017-08-31,0.0,Approved,Norco Bicycles,Standard,medium,medium,1198.46,381.10,36145.0
4,5,78,787,2017-10-01,1.0,Approved,Giant Bicycles,Standard,medium,large,1765.30,709.48,42226.0